Repository PetGoorm/frontend, pull requests merged in 2023-08, with the labels that each got.

#7 (layout: 메인페이지 및 로그인 창 레이아웃 변경)
  package.json
  src/components/main/BoardList.tsx
  src/components/main/Calender.tsx
  src/components/member/Login.tsx
  src/components/member/Signup.tsx
  src/custom.d.ts
  src/frame/Header.tsx
  src/frame/header/SearchBox.tsx
  src/index.js
  src/pages/Main.tsx
  src/styles/globalStyle.tsx
  src/styles/img/edit_logo2.png
  tsconfig.json
  yarn.lock
Labels: 🐞 BugFix, enhancement, ❄️FE, ✨ Feature

#9 (feat: mui-calendar 추가 및 Todolist 연동)
  package.json
  src/components/main/Calender.tsx
  src/components/todo/Calendar.tsx
  src/components/todo/Todolist.tsx
  src/frame/Header.tsx
  src/pages/Todo.tsx
  yarn.lock
Labels: ❄️FE, ✨ Feature

#10 (layout: 게시판 글 리스트, 등록 부분 추가)
  package.json
  src/App.js
  src/components/board/BoardForm.tsx
  src/components/board/BoardListAll.tsx
  src/components/board/CustomTable.tsx
  src/components/board/TablePaging.tsx
  src/data/dummy.json
  src/frame/Header.tsx
  src/pages/BoardFormPage.tsx
  src/pages/BoardListPage.tsx
  yarn.lock
Labels: enhancement, ❄️FE, ✨ Feature

#11 Feat: 게시판 기본 CRUD 기능 추가
  src/App.js
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardListAll.tsx
  src/components/board/BoardModifyForm.tsx
  src/components/board/boardImageUploader.tsx
  src/dto/boardRequestDto.tsx
  src/dto/boardResponseDto.tsx
  src/frame/Header.tsx
  src/pages/BoardCreatePage.tsx
  src/pages/BoardDetailPage.tsx
  src/pages/BoardListPage.tsx
  src/pages/BoardModifyPage.tsx
  yarn.lock
Labels: ✨ Feature

#12 (refacor: 자잘한 에러들 수정)
  src/components/member/Logout.tsx
  src/components/pet/PetForm.tsx
  src/frame/Header.tsx
  src/lib/useNicknameChecker.tsx
Labels: 🐞 BugFix, enhancement, ❄️FE, ✨ Feature
