Repository PetGoorm/frontend, pull requests merged in 2023-11, with the labels that each got.

#24 (feat: cicd 워크플로 파일 추가)
  .github/workflows/frontend.yml
Labels: ❄️FE, ✨ Feature, ⚙ Setting

#25 (fix: build error 수정)
  src/App.js
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardModifyForm.tsx
  src/components/board/boardImageUploader.tsx
  src/components/diary/Diary.tsx
  src/components/logo/Logo.js
  src/components/member/Logout.tsx
  src/components/member/mypage/EditNick.tsx
  src/components/member/mypage/EditPw.tsx
  src/components/pet/PetEdit.tsx
  src/components/pet/PetForm.tsx
  src/components/todo/Todofeed.tsx
  src/components/todo/Todolist.tsx
  src/layouts/dashboard/header/AccountPopover.js
  src/layouts/dashboard/nav/index.js
  src/lib/api.tsx
  src/pages/Main.js
  src/routes.js
Labels: 🐞 BugFix, ❄️FE

#26 (fix: 게시판 엔터로 검색 안되는 오류 수정, 게시물 댓글 컴포넌트 누락사항 재반영)
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/SeachBar.tsx
Labels: 🐞 BugFix
