Repository PetGoorm/frontend, pull requests merged in 2023-10, with the labels that each got.

#19 (feat: 페이지 레이아웃 수정, 댓글 기능 추가)
  src/App.js
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/Reply.tsx
  src/components/board/SeachBar.tsx
  src/components/logo/Logo.js
  src/components/member/Login.tsx
  src/components/member/Signup.tsx
  src/components/member/mypage/EditNick.tsx
  src/components/member/mypage/EditPw.tsx
  src/components/pet/PetEdit.tsx
  src/components/pet/PetForm.tsx
  src/components/pet/PetImgUpload.tsx
  src/layouts/dashboard/header/AccountPopover.js
  src/layouts/dashboard/nav/index.js
  src/layouts/dashboard/nav/navList.tsx
  src/pages/Main.js
  src/routes.js
Labels: enhancement, ❄️FE, ✨ Feature

#22 (feat: 반려일지 구현)
  src/components/diary/Diary.tsx
  src/components/diary/DiaryEdit.tsx
  src/layouts/dashboard/nav/navList.tsx
  src/pages/DiaryPage.tsx
  src/routes.js
Labels: ❄️FE, ✨ Feature

#23 (refactor & feat & fix) api 경로 수정, 메인 화면에 최신 게시물 조회 컴포넌트 추가, 게시물 생성 후 목록 돌아가기 기능 오류 해결
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardModifyForm.tsx
  src/components/board/RecentlyBoards.tsx
  src/components/member/Login.tsx
  src/components/member/Signup.tsx
  src/dto/boardResponseDto.tsx
  src/lib/api.tsx
  src/lib/useNicknameChecker.tsx
  src/pages/Main.js
  src/routes.js
  src/sections/@dashboard/app/AppNewsUpdate.js
Labels: 🐞 BugFix, ❄️FE, ✨ Feature, 🛠️ Refactor
