Repository PetGoorm/frontend, pull requests merged in 2023-09, with the labels that each got.

#14 (feat: 게시판 카테고리별 페이징, 글 없을 시 등장하는 오류 화면 추가)
  package.json
  src/App.js
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardForm.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardModifyForm.tsx
  src/components/board/Paging.tsx
  src/components/board/styles/ListStyle.css
  src/components/board/styles/Paging.css
  src/frame/Header.tsx
  src/pages/BoardListPage.tsx
  yarn.lock
Labels: ✨ Feature

#17 (feat: 캘린더 및 TODO 구현)
  package.json
  src/App.js
  src/components/calendar/Calendar.tsx
  src/components/calendar/calenderLeft.png
  src/components/calendar/calenderRight.png
  src/components/calendar/check.svg
  src/components/calendar/generateDate.ts
  src/components/calendar/styles.tsx
  src/components/main/Calender.tsx
  src/components/todo/Calendar.tsx
  src/components/todo/TodoInput.tsx
  src/components/todo/TodoItem.tsx
  src/components/todo/Todofeed.tsx
  src/components/todo/Todolist.tsx
  src/pages/Main.js
  src/pages/Todo.tsx
  src/routes.js
  src/stores/seletedDate.ts
  yarn.lock
Labels: ❄️FE, ✨ Feature

#16 (feat: 검색기능 및 로그인 기능 추가)
  src/components/board/BoardList.tsx
  src/components/board/SeachBar.tsx
  src/layouts/dashboard/DashboardLayout.js
  src/layouts/dashboard/header/AccountPopover.js
  src/layouts/dashboard/header/index.js
  src/layouts/dashboard/nav/config.js
  src/routes.js
Labels: enhancement, ❄️FE, ✨ Feature

#18 (feat: 게시판 조회수 표시, 글 삭제 시 confirm 추가, UI 소폭 수정)
  src/components/board/BoardCreateForm.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardModifyForm.tsx
  src/dto/boardResponseDto.tsx
  src/routes.js
Labels: ❄️FE, ✨ Feature
